name: Sumon Workflow

on: [push]

jobs:
    first-workflow:
        runs-on: windows-latest

        steps:
            - name: first step
              run: |
                echo "Hello World.!"
                echo "Md. Sumon Sarder"

