# name: CronJob Workflow

# on:
#     schedule:
#         - cron: "*/5 * * * *" #Run in every 5 min;

# jobs:
#     first-workflow:
#         runs-on: windows-latest

#         steps:
#             - name: first cronjob step
#               run: |
#                 echo "Hello Cron Job.!"
#                 echo "Md. Sumon Sarder.!"

