name: Value Pass Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter Your Name: "
        required: true
        default: "Sumon"

jobs:
  get-value-workflow-job:
    runs-on: windows-latest
    outputs:
      message: ${{ steps.generate-message.outputs.message }}  # Store output at job level

    steps:
      - name: Generate Greeting Message
        id: generate-message
        run: echo "message=Hello, ${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
        shell: bash  # Ensure compatibility

  print-value-workflow-job:
    runs-on: windows-latest
    needs: [get-value-workflow-job]

    steps:
      - name: Store Greeting Message (With Printing)
        run: |
          MESSAGE="${{ needs.get-value-workflow-job.outputs.message }}"
          echo "Generated Greeting: $MESSAGE"  # Print the message
        shell: bash
